var ActionNames = {
    CHANGE_LOADING: 'CHANGE_LOADING',

    CREATE_BOOK: 'CREATE_BOOK',
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAIL: 'CREATE_BOOK_FAIL',

    LOAD_BOOK: 'LOAD_BOOK',
    LOAD_BOOK_SUCCESS: 'LOAD_BOOK_SUCCESS',
    LOAD_BOOK_FAIL: 'LOAD_BOOK_FAIL',

    LOAD_BOOKS: 'LOAD_BOOKS',
    LOAD_BOOKS_SUCCESS: 'LOAD_BOOKS_SUCCESS',
    LOAD_BOOKS_FAIL: 'LOAD_BOOKS_FAIL',

    UPLOAD_FILE: 'UPLOAD_FILE',
    UPLOAD_FILE_PREVIEW: 'UPLOAD_FILE_PREVIEW',
    UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
    UPLOAD_FILE_PROGRESS: 'UPLOAD_FILE_PROGRESS',

    SEE_MORE_BOOKS: 'SEE_MORE_BOOKS'
};

module.exports = ActionNames;